### ISSUE TITLE
Scripting stuff

### ISSUE THREAD

**Issue by Doogie13** [lambda-client/lambda-legacy#132]
**Is your feature request related to a problem? Please describe.**
It would be easier to automate tasks and create simple modules (similar to source games like TF2 scripts)

**Describe the solution you'd like**
;Echo command to print a message to chat client side

;Wait command to pause a script for x ticks (would be affected by timer)

Ability to load scripts from files (essentially just macros but would be `;bind`able, with more work would show up in clickgui under seperate list with maybe settings like `%block wait 1 5 20%)

Syntax: `&[colour code]`, `//` and `/*  */`, `%[varName],[min],[default],[max]%`

**Describe alternatives you've considered**
plugin system (harder to use for code illiterate to use)

**Additional context**
Potential instantburrow script using packetcanceler CPacketPlayer to glitch down (tested concept on .cc): 
![image](https://user-images.githubusercontent.com/62295632/125199281-6177a900-e25d-11eb-8bed-6e52617cc867.png)

**Comment by Avanatiker** [comment]
I think its a cool idea to provide a scripting api but this in particular is a plugin by @ToxicAven

**Comment by Doogie13** [comment]
> 
> 
> I think its a cool idea to provide a scripting api but this in particular is a plugin by @ToxicAven

i dont think the plugin was finished but it was mostly a proof of concept
would be mostly useful for automating stuff , especially if using timer 20 or smth

**Comment by HoratioGamer** [comment]
(keywords are in CAPS, they do not need to be in caps in reality, just being clear as I am defining a language)

It needs comments

It needs  `IF ()/ELSEIF ()/ELSE/ENDIF` ,  `LOOP/ENDLOOP`,  `BREAK ()`, `CONTINUE ()`  and `END`.


It would really benefit from MATH, I recommend a stack that takes scalars or vectors or expressions as a text string, expression composed of RPN directives to perform a sequence of actions in RPN notation because it is really easy to code, and it works really well with the next idea.   The stack elements are a,b,c,d, etc.

`(expression)`  evaluates an expression using the current stack 
`LOCAL(expression)` evaluates an expression using a local stack, so that MARK and POPMARK are not needed.
`CONST(numbers)` evaluates as numbers ==> a
    then the value left in local/global stack position "a" at the end is the value of the EXPR, with an implied POP.
    
`EXPR(expression)` means put the expression as a string in stack position a and does not evaluate it except with an `EVAL` directive.

Define the following primitives: (inspired by PostScript, but with a couple extra to build, deconstruct and manipulate coordinate vectors): 

`DUPE POP EXCH                            `-- to manipulate the stack a,b,c, etc.  a is the current top of the stack, b is one down.
`ADD SUB MULT  DIV                       `-- defined for a,b vectors or scalars 
`SIN COS TAN ASIN ACOS ATAN  LN  LOG  EXP  EXP10   A^B  ` -- scalars only
`DOT                                                  `--   a.b ==> scalar
`X   Y   Z                                            `-- Extract a coordinate from a vector as a scalar 
`EXCH2                                             `--  a,b,c,d... ==> c,a,b,d,..  
`DUPEB                                             `--  a,b,c,d... ==> b,a,b,c,d...
`DUPEC                                             `--  a,b,c,d... ==> c,a,b,c,d...                                                 
`DUPED                                             `--  a,b,c,d... ==> d,a,b,c,d...
 (etc?)

`VECT                                              ` --  a,b,c ==> (a,b,c) ==> a, a vector
`CONST(numbers)  [variables]`                    

`NEAREST                                       `-- relative to the player COORDS, coordinates of the nearest block ID (a) ==> a
`BNEAREST                                    `-- relative to coords b, coordinates of the nearest block ID (a) ==> a

`RBLOCKID                                      `-- find the block ID of the block at the relative coordinates COORDS+a ==> a
`BLOCKID                                        `-- find the block ID of the block at the absolute coordinates a ==> a

`HAVE                                              `-- does one have block ID a in inventory/hotbar  ==> 1/0 ==> a
`==    >=    <=    !=   <  >                   `--  test a vs b ==> 1/0 ==> a
`CLEAR                                            `-- clear the stack
`MARK                                             `-- put a mark in the stack
`POPMARK                                     `-- pop back to the last MARK

`RPLACE                                          `-- relative place block ID a at COORDS+b ==> `POP POP` c==>a
`PLACE                                             `-- place block ID a at coordinates b ==> `POP POP` c==>a

`STRING                                          `-- if a is a scalar or a vector, this makes a into an expression `CONST(a)` 
`CONCAT                                         `-- concatenates two expressions b+" "+a ==> a

It needs game state variables that can be tested in conditions like `COORDS` and `TIME`:

`IF LOCAL(CONST(some coords) COORDS ==)  ` .....  



It would really benefit from a line-macro substitution a-la PostScript:

`/RANGE { PUSH COORDS SUB DUPE DOT }   def`

Then `IF ((const desired coords) RANGE CONST(10) < )`       checks if the player is within 10 blocks of desired coordinates

The decomposition of these macros into primitives is just by recursive text substitution, but it makes for a powerful, simple language with more and more complex functions used in single line expressions.   

It would be convenient if there were user variables.   
Variables inside {} are local to that {} all others are global.  


`SET variable EXPR(something to be evaluated later)`       or 
`SET variable CONST(scalar/vector)` or 
`SET variable ()`
`LSET variable () `                                                             -- create&set a local variable valid in this context

If variable1 is an expression:
`SET variable2 ([variable1] EVAL)`                                          does evaluate the expression
`SET variable2 ([variable1] EXPR(more) CONCAT)`               does not evaluate the expression




Then a wait with timeout becomes:

```
SET  tstart   (TIME)
SET timeout CONST(0)
LOOP
    IF (some completed condition)   BREAK (1)  ENDIF                     // could be written as separate lines, does not matter.
    IF (TIME [tstart] SUB CONST(10) <) 
        SET timeout CONST(1) 
        BREAK (1)
    ENDIF
ENDLOOP

```
...

`BREAK (1)` is like the regular break; in C.... but `BREAK (2)` means break out of this loop AND the outer loop too.   A break / continue capable of busting out of inner loops and resuming an outer one replaces a lot of temporary variables, and if statements or a `LABEL/GOTO` statement that breaks strict nesting.

`IF (), ELSEIF (), SET () and LSET ()` imply a `POP` of the result, unless `LOCAL()` is used.  If one writes ordinary expressions to accomplish for instance `(M==N)` as `([M] [N] ==) `with the implied `POP` these are stack-neutral.  `LOCAL` assures they are stack-neutral, but also, they cannot access variables in the global stack, only `[variables]`.   If LOCAL is not used and the expressions access the stack, they have to take care of being stack neutral or control stack usage.

```
/ACTWAITFOR {
   LSET action (DUPEC)                                           // Action expression
   LSET test     (DUPEB)                                           // test to see if the action was successful
   LSET timeout (DUPE)                                           // timeout
   POP POP POP                                                     // Make sure this is stack-neutral
   
   [action] EVAL                                                                   
   LSET  tstart   (TIME)
   LOOP
       IF ([test] EVAL)   
           CONST(1)  
           BREAK (1)  
       ENDIF                    
       IF (TIME   [tstart]   SUB   [timeout] <)  
           CONST(0)
           BREAK (1)
       ENDIF
   ENDLOOP
} def

```
`ACTWAITFOR` is now a subroutine that executes code inside another expression.   

`IF ( EXPR(action) EXPR(wait condition)  CONST(timeout)    ACTWAITFOR  )`   or
`SET success ( EXPR(action)  EXPR(wait condition) CONST(timeout)    ACTWAITFOR  )`

This is a flat language, expressions, keywords it does not matter, the interpreter knows what to do in any case.   Algorithm statements can appear within the brackets of a `SET ()`, `LSET ()`, `IF ()` or `ELSEIF ()` statement..

The only syntax errors are no keyword found, or an `END-type` or `ELSEIF` statement without the first statement in the block -- a nesting error.

The only runtime errors are variable does not exist, divide by zero, `TAN` 90, `LN`/`LOG` of zero, and stack empty.

`IF ()` 

is a valid piece of code if there is a value in the stack -- it means take the value at the top of the stack, 0 is false, any non-zero non-scalar is true, and use that to decide what code to execute.

I have programmed several such languages before, it is easily done, in C ... surely the great and powerful Java can knock out something as linear as reading through the lines of a file, interpreting it in a linear fashion.

**Comment by HoratioGamer** [comment]
^ without order or operations, or fancy procedures or data structures, this language can do math, execute algorithm, even self-author code,   

It would be kind of handy if it had lists of items... so you could build lists and knock them off one at a time.
Or a variable that is a stack.... and stack operations.

**Comment by Avanatiker** [comment]
Very creative Horatio! sadly i dont think there is a real benefit to just code a plugin. If anyone wanna code a plugin for it have fun :D
