### ISSUE TITLE
crashes with my other clients 

### ISSUE THREAD

**Issue by spazmilk** [lambda-client/lambda-legacy#141]
[latest.log](https://github.com/lambda-client/lambda/files/7029071/latest.log)
crashes with rusher and konas

**Comment by scorbett123** [comment]
Rename Konas to !konas

**Comment by spazmilk** [comment]
> Rename Konas to !konas

nope still crashes :(

**Comment by Dogcube51** [comment]
I dont really know what Konas is but that likely means either 1 konas has the same modid as lambda and the second thing its just a guess but if another client uses baritone it could crash because of that? also did can you isolate the problem or is it both rusherhack and konas that crash because that could narrow it down to the client that is causing the issue with lambda

**Comment by spazmilk** [comment]
> I dont really know what Konas is but that likely means either 1 konas has the same modid as lambda and the second thing its just a guess but if another client uses baritone it could crash because of that? also did can you isolate the problem or is it both rusherhack and konas that crash because that could narrow it down to the client that is causing the issue with lambda

its konas ive submitted a report in konas discord. rusherhack is compatible

**Comment by Doogie13** [comment]
rename lambda to !lambda

**Comment by Doogie13** [comment]
kotlin thing

**Comment by spazmilk** [comment]
> rename lambda to !lambda

❤️
